### ISSUE TITLE
Deploy to Function App Script Failed on (intermediate value).parsedBody.map is not a function

### ISSUE THREAD

**Issue by BillmanH** [microsoft/vscode-azurefunctions#3769]
Using AZ function deploy (1.12.1) deploy:
![image](https://github.com/microsoft/vscode-azurefunctions/assets/10108711/ddc6c917-66cb-4aa5-ab25-060ad4bbdbeb)

Crashes on final step:
`(intermediate value).parsedBody.map is not a function`

Reverting to `1.10.4` solved this problem. 

Windows, current
VS code, current

**Comment by timkishkin** [comment]
Happens to me as well, but randomly. Sometimes restarting the deployment process helps, but not reliably

**Comment by ayoub377** [comment]
Yes it do occur sometimes I figured that restarting vs code helps

**Comment by paritoshromy** [comment]
I am facing similar erratic issues for Azure Web App deployment and restarting VS Code fixes this at times

**Comment by michal-husak** [comment]
me too

**Comment by michaelmarziani** [comment]
I have started seeing this error at random when deploying to Azure App Service.

This error started in the past couple weeks or so. I'd never seen it before, and in general never had problems with Azure App Service deployments from VS Code.

Thus far if I re-run the deployment after getting the error, it works, but I find it unsettling to see random errors in a deployment procedure.

**Comment by BillmanH** [comment]
In my case, re running didn't solve the problem. However I only tried a few time before reverting. I also tried several iterations back before eventually landing on 1.10.4.  So it could be that it just ran and the version wasn't the issue. However  in 1.10.4 I haven't had the issue.

**Comment by ARTEAGA1811** [comment]
just restart VS code and it will work  :)

**Comment by danmalone89** [comment]
Restarting VS Code is not working for me.

**Comment by BillmanH** [comment]
> just restart VS code and it will work :)

Not reliably

**Comment by SzymonSel** [comment]
Same here :|

**Comment by alexweininger** [comment]
Can anyone share the contents of the output channel when this error occurs? It'll help me figure out which call is causing the error.

**Comment by dfuchs-hitachi** [comment]
```
10:06:26 AM: Failed to get latest templates: Cannot read properties of undefined (reading 'resources')
10:07:04 AM mycompany-dev-integrations-func: Starting deployment...
10:07:05 AM mycompany-dev-integrations-func: Creating zip package...
10:07:14 AM mycompany-dev-integrations-func: Zip package size: 25.2 MB
10:07:18 AM: Error: (intermediate value).parsedBody.map is not a function
```

**Comment by alexweininger** [comment]
@dfuchs-hitachi, thanks for providing the logs. We've fixed this in https://github.com/microsoft/vscode-azuretools/pull/1545 and hope to release it soon.

**Comment by thecury** [comment]
> @dfuchs-hitachi, thanks for providing the logs. We've fixed this in [microsoft/vscode-azuretools#1545](https://github.com/microsoft/vscode-azuretools/pull/1545) and hope to release it soon.

Is there any workaround in the interim?

**Comment by adriennn** [comment]
for me the error occurs at

```
3:39:14 PM func-myfunc-dev-we-001: Preparing output...
3:39:14 PM func-myfunc-dev-we-001: Copying files to destination directory '/tmp/build/expressbuild'...
3:39:25 PM func-myfunc-dev-we-001: Done in 11 sec(s).
3:39:25 PM func-myfunc-dev-we-001: Removing existing manifest file
3:39:25 PM func-myfunc-dev-we-001: Creating a manifest file...
3:39:25 PM func-myfunc-dev-we-001: Manifest file created.
3:39:25 PM func-myfunc-dev-we-001: Copying .ostype to manifest output directory.
3:39:25 PM func-myfunc-dev-we-001: Done in 178 sec(s).
3:39:37 PM: Error: (intermediate value).parsedBody.map is not a function
```

and reverting to v1.11.0 worked

@thecury, revert to a previous extension version, it's a simple click away.

**Comment by alexweininger** [comment]
Fixed by https://github.com/microsoft/vscode-azurefunctions/pull/3786

**Comment by BillmanH** [comment]
Confirmed that `v1.12.3` seems to be working. Thanks!

**Comment by SzymonSel** [comment]
Thanks!

**Comment by dluc** [comment]
Still happening for web apps

VS Code: 1.81.1
Azure Tools: 1.2.0
Azure App Service: 0.25.0

**Comment by alexweininger** [comment]
> Still happening for web apps
> 
> VS Code: 1.81.1 Azure Tools: 1.2.0 Azure App Service: 0.25.0

Sorry about that. The fix has been released in Functions, however is still waiting to be released in App Service.
